trigger:
  - master

stages:
  - stage: build_stage
    displayName: "Build"
    jobs:
      - job: build_job
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'Docker Hub'
            repository: 'darlorob/lcars'
            command: 'buildAndPush'
            Dockerfile: '**/Server/**/Dockerfile'
            buildContext: '$(Build.Repository.LocalPath)'